name: ARO_Practical
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - numpy=1.19.1
  - pip=20.2.2
  - python=3.6.11
  - pyyaml=5.3.1
  - scipy=1.5.2
  - setuptools=49.6.0
  - yaml=0.2.5
  - pip:
    - pybullet==2.8.7
prefix: /opt/anaconda3/envs/ARO_Practical
